# Generated by Django 3.2.5 on 2021-08-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0011_auto_20210822_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrunquestions',
            name='is_right',
            field=models.BooleanField(default=False),
        ),
    ]
