# Generated by Django 3.2.6 on 2021-08-10 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0010_auto_20210810_0056'),
        ('tests_app', '0011_auto_20210806_2041'),
    ]

    operations = [
    ]
